# Github action define for test each major OS and show test result automatically
name: cover-checker test and get coverage

on:
  pull_request:
    branches: [ master ]
    types: [opened, synchronize, reopened, edited, ready_for_review, review_requested]

jobs:
  test-linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Maven
      run: mvn clean package
    - name: comment coverage report
      shell: bash
      env:
        ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: java -jar ./cover-checker-console/target/cover-checker-console-1.4.0-jar-with-dependencies.jar -c ./cover-checker-cobertura/target/site/jacoco -c ./cover-checker-console/target/site/jacoco -c ./cover-checker-core/target/site/jacoco/ -c ./cover-checker-github/target/site/jacoco -c ./cover-checker-jacoco/target/site/jacoco -t 80 -r $GITHUB_REPOSITORY -g $ACCESS_TOKEN -p $(echo $GITHUB_REF | awk 'BEGIN { FS = "/" } ; { print $3 }')
  test-macos:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Maven
      run: mvn clean package
# test-window:
#   runs-on: windows-latest
#   steps:
#   - uses: actions/checkout@v2
#   - name: Set up JDK 1.8
#     uses: actions/setup-java@v1
#     with:
#       java-version: 1.8
#   - name: Build with Maven
#     run: mvn clean package